apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${REPO_NAME}-demo-flux
  namespace: default
  labels:
    app: ${REPO_NAME}-demo-flux
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${REPO_NAME}-demo-flux
  template:
    metadata:
      labels:
        app: ${REPO_NAME}-demo-flux  
    spec:
      containers:
      - name: ${REPO_NAME}-demo-flux
        image: ${ECR_REGISTRY}:${TAG_IMAGE}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
